//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourcesDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaMasterChild
    {
        public long MediaMasterChildID { get; set; }
        public long MediaID { get; set; }
        public long MediaIDChild { get; set; }
    
        public virtual Media Media { get; set; }
        public virtual Media Media1 { get; set; }
    }
}
