//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SourcesDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Media
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Media()
        {
            this.MediaMasterChild = new HashSet<MediaMasterChild>();
            this.MediaMasterChild1 = new HashSet<MediaMasterChild>();
        }
    
        public long MediaID { get; set; }
        public string PRNewswireID { get; set; }
        public Nullable<int> JumboPilotID { get; set; }
        public Nullable<int> MediaScoreID { get; set; }
        public string MediaName { get; set; }
        public bool DigitalRights { get; set; }
        public bool MorningInfo { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string WebSite { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxNumber { get; set; }
        public string Email { get; set; }
        public string Description { get; set; }
        public Nullable<long> MapCountryID { get; set; }
        public Nullable<long> MapPeriodicityID { get; set; }
        public Nullable<long> MapMediaTypeID { get; set; }
        public Nullable<long> MapFormatID { get; set; }
        public Nullable<long> MapCategoryID { get; set; }
        public Nullable<long> MapCalendarTypeID { get; set; }
        public Nullable<long> MapDeliveryMethodID { get; set; }
        public Nullable<long> MapFocusID { get; set; }
        public Nullable<long> PublisherID { get; set; }
        public string Remarks { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public bool UpdateMS { get; set; }
        public bool UpdateJP { get; set; }
        public bool UpdateLanguageJP { get; set; }
        public bool UpdateFigureJP { get; set; }
        public bool UpdateFigureMS { get; set; }
        public bool UpdateGroupJP { get; set; }
        public bool ActiveJP { get; set; }
        public bool ActiveMS { get; set; }
        public string CreatedBy { get; set; }
        public string ModBy { get; set; }
        public Nullable<long> ParentID { get; set; }
        public bool RefreshAllFigures { get; set; }
        public Nullable<int> SeqLength { get; set; }
        public Nullable<short> NbOfCuttings { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<short> Texthandling { get; set; }
        public Nullable<short> RealPDF { get; set; }
        public Nullable<bool> GoPress { get; set; }
        public string FolderGoPress { get; set; }
        public Nullable<bool> PublicationMaster { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaMasterChild> MediaMasterChild { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MediaMasterChild> MediaMasterChild1 { get; set; }
    }
}
