//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntegrationPdfGoPressDB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PublicationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PublicationMaster()
        {
            this.PublicationMasterChild = new HashSet<PublicationMasterChild>();
        }
    
        public long PublicationMasterID { get; set; }
        public string PublicationName { get; set; }
        public long MediaID { get; set; }
        public string MediaName { get; set; }
        public Nullable<bool> Master { get; set; }
        public string RepositorySource { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PublicationMasterChild> PublicationMasterChild { get; set; }
    }
}
